CSV One

In [2]:
import pandas as pd
# Path to first CSV file
file_path = r"C:\Users\khali\Synoptic Project\gz2_filename_mapping.csv"
# Load CSV into a DataFrame
df = pd.read_csv(file_path)
# Show first 5 rows 
df.head()

                objid    sample  asset_id
0  587722981736120347  original         1
1  587722981736579107  original         2
2  587722981741363294  original         3
3  587722981741363323  original         4
4  587722981741559888  original         5

CSV Two

In [3]:
import pandas as pd
# Path to second dataset that is gz file
file_path1 = r"C:\Users\khali\Synoptic Project\gz2_hart16.csv.gz"
# Load compressed CSV file
df1 = pd.read_csv(file_path1, compression='gzip')
# Show first 5 rows
df1.head()

,dr7objid,ra,dec,rastring,decstring,sample,gz2_class,total_classifications,total_votes,t01_smooth_or_features_a01_smooth_count,...,t11_arms_number_a36_more_than_4_fraction,t11_arms_number_a36_more_than_4_weighted_fraction,t11_arms_number_a36_more_than_4_debiased,t11_arms_number_a36_more_than_4_flag,t11_arms_number_a37_cant_tell_count,t11_arms_number_a37_cant_tell_weight,t11_arms_number_a37_cant_tell_fraction,t11_arms_number_a37_cant_tell_weighted_fraction,t11_arms_number_a37_cant_tell_debiased,t11_arms_number_a37_cant_tell_flag
0,587732591714893851,179.042984,60.522518,11:56:10.32,+60:31:21.1,original,Sc+t,45,342,0,...,0.450,0.450,0.482646,0,16,16.0,0.400,0.400,0.394506,0
1,588009368545984617,135.084396,52.494240,09:00:20.26,+52:29:39.3,original,Sb+t,42,332,1,...,0.512,0.503,0.504833,0,13,13.0,0.317,0.323,0.322743,0
2,587732484359913515,183.371979,50.741508,12:13:29.27,+50:44:29.4,original,Ei,36,125,28,...,0.000,0.000,0.000000,0,0,0.0,0.000,0.000,0.000000,0
3,587741723357282317,186.251953,28.558598,12:25:00.47,+28:33:31.0,original,Sc+t,28,218,1,...,0.240,0.240,0.241322,0,6,6.0,0.240,0.240,0.239765,0
4,587738410866966577,161.086395,14.084465,10:44:20.73,+14:05:04.1,original,Er,43,151,33,...,0.000,0.000,0.000000,0,0,0.0,0.000,0.000,0.000000,0

Column Detail

In [4]:
# Get all unique galaxy classes
sorted(df1['gz2_class'].unique())

['A',
 'Ec',
 'Ec(d)',
 'Ec(i)',
 'Ec(l)',
 'Ec(m)',
 'Ec(o)',
 'Ec(r)',
 'Ec(u)',
 'Ei',
 'Ei(d)',
 'Ei(i)',
 'Ei(l)',
 'Ei(m)',
 'Ei(o)',
 'Ei(r)',
 'Ei(u)',
 'Er',
 'Er(d)',
 'Er(i)',
 'Er(l)',
 'Er(m)',
 'Er(o)',
 'Er(r)',
 'Er(u)',
 'SBa',
 'SBa(d)',
 'SBa(i)',
 'SBa(m)',
 'SBa(o)',
 'SBa(r)',
 'SBa+m',
 'SBa+t',
 'SBa+t(o)',
 'SBa1l',
 'SBa1l(m)',
 'SBa1l(u)',
 'SBa1m',
 'SBa1t',
 'SBa1t(i)',
 'SBa2l',
 'SBa2l(m)',
 'SBa2l(r)',
 'SBa2m',
 'SBa2m(i)',
 'SBa2m(m)',
 'SBa2m(r)',
 'SBa2t',
 'SBa2t(i)',
 'SBa2t(l)',
 'SBa2t(r)',
 'SBa3l(r)',
 'SBa3t',
 'SBa4m',
 'SBa?l',
 'SBa?m',
 'SBa?m(m)',
 'SBa?t',
 'SBa?t(o)',
 'SBa?t(r)',
 'SBb',
 'SBb(d)',
 'SBb(i)',
 'SBb(l)',
 'SBb(m)',
 'SBb(o)',
 'SBb(r)',
 'SBb(u)',
 'SBb+l',
 'SBb+l(i)',
 'SBb+l(m)',
 'SBb+l(o)',
 'SBb+l(r)',
 'SBb+m',
 'SBb+m(i)',
 'SBb+m(m)',
 'SBb+m(o)',
 'SBb+m(r)',
 'SBb+t',
 'SBb+t(d)',
 'SBb+t(i)',
 'SBb+t(m)',
 'SBb+t(o)',
 'SBb+t(r)',
 'SBb1l',
 'SBb1l(d)',
 'SBb1l(i)',
 'SBb1l(l)',
 'SBb1l(m)',
 'SBb1l(o)',
 'SBb1l(r)',
 'SBb1l(u)',
 'SBb1m',
 'SBb1m(d)',
 'SBb1m(i)',
 'SBb1m(m)',
 'SBb1m(o)',
 'SBb1m(r)',
 'SBb1m(u)',
 'SBb1t',
 'SBb1t(d)',
 'SBb1t(i)',
 'SBb1t(l)',
 'SBb1t(m)',
 'SBb1t(o)',
 'SBb1t(r)',
 'SBb1t(u)',
 'SBb2l',
 'SBb2l(d)',
 'SBb2l(i)',
 'SBb2l(l)',
 'SBb2l(m)',
 'SBb2l(o)',
 'SBb2l(r)',
 'SBb2l(u)',
 'SBb2m',
 'SBb2m(d)',
 'SBb2m(i)',
 'SBb2m(l)',
 'SBb2m(m)',
 'SBb2m(o)',
 'SBb2m(r)',
 'SBb2m(u)',
 'SBb2t',
 'SBb2t(d)',
 'SBb2t(i)',
 'SBb2t(l)',
 'SBb2t(m)',
 'SBb2t(o)',
 'SBb2t(r)',
 'SBb2t(u)',
 'SBb3l',
 'SBb3l(d)',
 'SBb3l(i)',
 'SBb3l(m)',
 'SBb3l(r)',
 'SBb3m',
 'SBb3m(d)',
 'SBb3m(i)',
 'SBb3m(m)',
 'SBb3m(o)',
 'SBb3m(r)',
 'SBb3m(u)',
 'SBb3t',
 'SBb3t(d)',
 'SBb3t(i)',
 'SBb3t(l)',
 'SBb3t(m)',
 'SBb3t(o)',
 'SBb3t(r)',
 'SBb3t(u)',
 'SBb4l',
 'SBb4l(d)',
 'SBb4l(i)',
 'SBb4l(m)',
 'SBb4l(r)',
 'SBb4m',
 'SBb4m(d)',
 'SBb4m(i)',
 'SBb4m(m)',
 'SBb4m(o)',
 'SBb4m(r)',
 'SBb4t',
 'SBb4t(d)',
 'SBb4t(i)',
 'SBb4t(l)',
 'SBb4t(m)',
 'SBb4t(o)',
 'SBb4t(r)',
 'SBb4t(u)',
 'SBb?l',
 'SBb?l(d)',
 'SBb?l(i)',
 'SBb?l(l)',
 'SBb?l(m)',
 'SBb?l(o)',
 'SBb?l(r)',
 'SBb?l(u)',
 'SBb?m',
 'SBb?m(d)',
 'SBb?m(i)',
 'SBb?m(l)',
 'SBb?m(m)',
 'SBb?m(o)',
 'SBb?m(r)',
 'SBb?m(u)',
 'SBb?t',
 'SBb?t(d)',
 'SBb?t(i)',
 'SBb?t(l)',
 'SBb?t(m)',
 'SBb?t(o)',
 'SBb?t(r)',
 'SBb?t(u)',
 'SBc',
 'SBc(d)',
 'SBc(i)',
 'SBc(l)',
 'SBc(m)',
 'SBc(o)',
 'SBc(r)',
 'SBc(u)',
 'SBc+l',
 'SBc+l(d)',
 'SBc+l(i)',
 'SBc+l(m)',
 'SBc+l(o)',
 'SBc+m',
 'SBc+m(d)',
 'SBc+m(i)',
 'SBc+m(m)',
 'SBc+m(o)',
 'SBc+m(r)',
 'SBc+t',
 'SBc+t(d)',
 'SBc+t(i)',
 'SBc+t(m)',
 'SBc+t(o)',
 'SBc+t(r)',
 'SBc1l',
 'SBc1l(d)',
 'SBc1l(i)',
 'SBc1l(l)',
 'SBc1l(m)',
 'SBc1l(o)',
 'SBc1l(r)',
 'SBc1m',
 'SBc1m(d)',
 'SBc1m(i)',
 'SBc1m(l)',
 'SBc1m(m)',
 'SBc1m(o)',
 'SBc1m(r)',
 'SBc1m(u)',
 'SBc1t',
 'SBc1t(d)',
 'SBc1t(i)',
 'SBc1t(m)',
 'SBc1t(o)',
 'SBc1t(r)',
 'SBc1t(u)',
 'SBc2l',
 'SBc2l(d)',
 'SBc2l(i)',
 'SBc2l(l)',
 'SBc2l(m)',
 'SBc2l(o)',
 'SBc2l(r)',
 'SBc2l(u)',
 'SBc2m',
 'SBc2m(d)',
 'SBc2m(i)',
 'SBc2m(l)',
 'SBc2m(m)',
 'SBc2m(o)',
 'SBc2m(r)',
 'SBc2m(u)',
 'SBc2t',
 'SBc2t(d)',
 'SBc2t(i)',
 'SBc2t(l)',
 'SBc2t(m)',
 'SBc2t(o)',
 'SBc2t(r)',
 'SBc2t(u)',
 'SBc3l',
 'SBc3l(d)',
 'SBc3l(i)',
 'SBc3l(m)',
 'SBc3l(o)',
 'SBc3l(r)',
 'SBc3m',
 'SBc3m(d)',
 'SBc3m(i)',
 'SBc3m(l)',
 'SBc3m(m)',
 'SBc3m(o)',
 'SBc3m(r)',
 'SBc3m(u)',
 'SBc3t',
 'SBc3t(d)',
 'SBc3t(i)',
 'SBc3t(l)',
 'SBc3t(m)',
 'SBc3t(o)',
 'SBc3t(r)',
 'SBc3t(u)',
 'SBc4l',
 'SBc4l(d)',
 'SBc4l(i)',
 'SBc4l(l)',
 'SBc4l(m)',
 'SBc4l(r)',
 'SBc4m',
 'SBc4m(d)',
 'SBc4m(i)',
 'SBc4m(m)',
 'SBc4m(o)',
 'SBc4m(r)',
 'SBc4t',
 'SBc4t(d)',
 'SBc4t(i)',
 'SBc4t(l)',
 'SBc4t(m)',
 'SBc4t(o)',
 'SBc4t(r)',
 'SBc4t(u)',
 'SBc?l',
 'SBc?l(d)',
 'SBc?l(i)',
 'SBc?l(m)',
 'SBc?l(o)',
 'SBc?l(r)',
 'SBc?m',
 'SBc?m(d)',
 'SBc?m(i)',
 'SBc?m(l)',
 'SBc?m(m)',
 'SBc?m(o)',
 'SBc?m(r)',
 'SBc?m(u)',
 'SBc?t',
 'SBc?t(d)',
 'SBc?t(i)',
 'SBc?t(l)',
 'SBc?t(m)',
 'SBc?t(o)',
 'SBc?t(r)',
 'SBc?t(u)',
 'SBd',
 'SBd(d)',
 'SBd(i)',
 'SBd(m)',
 'SBd(o)',
 'SBd(r)',
 'SBd(u)',
 'SBd+m',
 'SBd+m(i)',
 'SBd+t',
 'SBd+t(i)',
 'SBd+t(r)',
 'SBd1l',
 'SBd1l(d)',
 'SBd1l(i)',
 'SBd1l(m)',
 'SBd1l(o)',
 'SBd1m',
 'SBd1m(i)',
 'SBd1m(m)',
 'SBd1t',
 'SBd1t(i)',
 'SBd2l',
 'SBd2l(d)',
 'SBd2l(i)',
 'SBd2l(m)',
 'SBd2l(o)',
 'SBd2m',
 'SBd2m(d)',
 'SBd2m(i)',
 'SBd2m(m)',
 'SBd2m(o)',
 'SBd2m(u)',
 'SBd2t',
 'SBd2t(i)',
 'SBd2t(r)',
 'SBd2t(u)',
 'SBd3l',
 'SBd3l(i)',
 'SBd3m',
 'SBd3m(i)',
 'SBd3t',
 'SBd3t(d)',
 'SBd4l(i)',
 'SBd4m',
 'SBd4t',
 'SBd?l',
 'SBd?l(d)',
 'SBd?l(i)',
 'SBd?l(o)',
 'SBd?m',
 'SBd?m(d)',
 'SBd?m(i)',
 'SBd?m(o)',
 'SBd?t',
 'SBd?t(d)',
 'SBd?t(i)',
 'SBd?t(m)',
 'SBd?t(o)',
 'SBd?t(r)',
 'Sa',
 'Sa(d)',
 'Sa(i)',
 'Sa(l)',
 'Sa(m)',
 'Sa(o)',
 'Sa(r)',
 'Sa(u)',
 'Sa+l',
 'Sa+m',
 'Sa+t',
 'Sa+t(o)',
 'Sa+t(r)',
 'Sa1l',
 'Sa1l(d)',
 'Sa1l(i)',
 'Sa1l(m)',
 'Sa1l(r)',
 'Sa1m',
 'Sa1m(d)',
 'Sa1m(i)',
 'Sa1m(o)',
 'Sa1m(r)',
 'Sa1t',
 'Sa1t(o)',
 'Sa2l',
 'Sa2l(d)',
 'Sa2l(m)',
 'Sa2l(o)',
 'Sa2l(r)',
 'Sa2m',
 'Sa2m(m)',
 'Sa2m(r)',
 'Sa2t',
 'Sa2t(i)',
 'Sa2t(o)',
 'Sa2t(r)',
 'Sa3l(i)',
 'Sa3l(r)',
 'Sa3m',
 'Sa3m(d)',
 'Sa3t',
 'Sa4l',
 'Sa4t',
 'Sa?l',
 'Sa?l(i)',
 'Sa?l(m)',
 'Sa?l(r)',
 'Sa?m',
 'Sa?m(m)',
 'Sa?m(o)',
 'Sa?t',
 'Sa?t(d)',
 'Sa?t(m)',
 'Sa?t(o)',
 'Sa?t(r)',
 'Sb',
 'Sb(d)',
 'Sb(i)',
 'Sb(l)',
 'Sb(m)',
 'Sb(o)',
 'Sb(r)',
 'Sb(u)',
 'Sb+l',
 'Sb+l(l)',
 'Sb+l(m)',
 'Sb+l(o)',
 'Sb+l(r)',
 'Sb+m',
 'Sb+m(d)',
 'Sb+m(i)',
 'Sb+m(l)',
 'Sb+m(m)',
 'Sb+m(o)',
 'Sb+m(r)',
 'Sb+t',
 'Sb+t(d)',
 'Sb+t(i)',
 'Sb+t(l)',
 'Sb+t(m)',
 'Sb+t(o)',
 'Sb+t(r)',
 'Sb+t(u)',
 'Sb1l',
 'Sb1l(d)',
 'Sb1l(i)',
 'Sb1l(l)',
 'Sb1l(m)',
 'Sb1l(o)',
 'Sb1l(r)',
 'Sb1l(u)',
 'Sb1m',
 'Sb1m(d)',
 'Sb1m(i)',
 'Sb1m(l)',
 'Sb1m(m)',
 'Sb1m(o)',
 'Sb1m(r)',
 'Sb1m(u)',
 'Sb1t',
 'Sb1t(d)',
 'Sb1t(i)',
 'Sb1t(l)',
 'Sb1t(m)',
 'Sb1t(o)',
 'Sb1t(r)',
 'Sb1t(u)',
 'Sb2l',
 'Sb2l(d)',
 'Sb2l(i)',
 'Sb2l(l)',
 'Sb2l(m)',
 'Sb2l(o)',
 'Sb2l(r)',
 'Sb2l(u)',
 'Sb2m',
 'Sb2m(d)',
 'Sb2m(i)',
 'Sb2m(m)',
 'Sb2m(o)',
 'Sb2m(r)',
 'Sb2m(u)',
 'Sb2t',
 'Sb2t(d)',
 'Sb2t(i)',
 'Sb2t(l)',
 'Sb2t(m)',
 'Sb2t(o)',
 'Sb2t(r)',
 'Sb2t(u)',
 'Sb3l',
 'Sb3l(d)',
 'Sb3l(i)',
 'Sb3l(m)',
 'Sb3l(o)',
 'Sb3l(r)',
 'Sb3m',
 'Sb3m(d)',
 'Sb3m(i)',
 'Sb3m(l)',
 'Sb3m(m)',
 'Sb3m(o)',
 'Sb3m(r)',
 'Sb3m(u)',
 'Sb3t',
 'Sb3t(d)',
 'Sb3t(i)',
 'Sb3t(m)',
 'Sb3t(o)',
 'Sb3t(r)',
 'Sb3t(u)',
 'Sb4l',
 'Sb4l(d)',
 'Sb4l(i)',
 'Sb4l(m)',
 'Sb4l(r)',
 'Sb4m',
 'Sb4m(i)',
 'Sb4m(m)',
 'Sb4m(o)',
 'Sb4m(r)',
 'Sb4m(u)',
 'Sb4t',
 'Sb4t(i)',
 'Sb4t(m)',
 'Sb4t(o)',
 'Sb4t(r)',
 'Sb?l',
 'Sb?l(d)',
 'Sb?l(i)',
 'Sb?l(l)',
 'Sb?l(m)',
 'Sb?l(o)',
 'Sb?l(r)',
 'Sb?l(u)',
 'Sb?m',
 'Sb?m(d)',
 'Sb?m(i)',
 'Sb?m(l)',
 'Sb?m(m)',
 'Sb?m(o)',
 'Sb?m(r)',
 'Sb?m(u)',
 'Sb?t',
 'Sb?t(d)',
 'Sb?t(i)',
 'Sb?t(l)',
 'Sb?t(m)',
 'Sb?t(o)',
 'Sb?t(r)',
 'Sb?t(u)',
 'Sc',
 'Sc(d)',
 'Sc(i)',
 'Sc(l)',
 'Sc(m)',
 'Sc(o)',
 'Sc(r)',
 'Sc(u)',
 'Sc+l',
 'Sc+l(i)',
 'Sc+l(m)',
 'Sc+l(o)',
 'Sc+l(r)',
 'Sc+m',
 'Sc+m(d)',
 'Sc+m(i)',
 'Sc+m(m)',
 'Sc+m(o)',
 'Sc+m(r)',
 'Sc+t',
 'Sc+t(d)',
 'Sc+t(i)',
 'Sc+t(l)',
 'Sc+t(m)',
 'Sc+t(o)',
 'Sc+t(r)',
 'Sc1l',
 'Sc1l(d)',
 'Sc1l(i)',
 'Sc1l(l)',
 'Sc1l(m)',
 'Sc1l(o)',
 'Sc1l(r)',
 'Sc1l(u)',
 'Sc1m',
 'Sc1m(d)',
 'Sc1m(i)',
 'Sc1m(l)',
 'Sc1m(m)',
 'Sc1m(o)',
 'Sc1m(r)',
 'Sc1m(u)',
 'Sc1t',
 'Sc1t(d)',
 'Sc1t(i)',
 'Sc1t(l)',
 'Sc1t(m)',
 'Sc1t(o)',
 'Sc1t(r)',
 'Sc1t(u)',
 'Sc2l',
 'Sc2l(d)',
 'Sc2l(i)',
 'Sc2l(l)',
 'Sc2l(m)',
 'Sc2l(o)',
 'Sc2l(r)',
 'Sc2l(u)',
 'Sc2m',
 'Sc2m(d)',
 'Sc2m(i)',
 'Sc2m(l)',
 'Sc2m(m)',
 'Sc2m(o)',
 'Sc2m(r)',
 'Sc2m(u)',
 'Sc2t',
 'Sc2t(d)',
 'Sc2t(i)',
 'Sc2t(l)',
 'Sc2t(m)',
 'Sc2t(o)',
 'Sc2t(r)',
 'Sc2t(u)',
 'Sc3l',
 'Sc3l(d)',
 'Sc3l(i)',
 'Sc3l(m)',
 'Sc3l(o)',
 'Sc3l(r)',
 'Sc3l(u)',
 'Sc3m',
 'Sc3m(d)',
 'Sc3m(i)',
 'Sc3m(l)',
 'Sc3m(m)',
 'Sc3m(o)',
 'Sc3m(r)',
 'Sc3t',
 'Sc3t(d)',
 'Sc3t(i)',
 'Sc3t(l)',
 'Sc3t(m)',
 'Sc3t(o)',
 'Sc3t(r)',
 'Sc3t(u)',
 'Sc4l',
 'Sc4l(d)',
 'Sc4l(i)',
 'Sc4l(m)',
 'Sc4l(r)',
 'Sc4m',
 'Sc4m(d)',
 'Sc4m(i)',
 'Sc4m(l)',
 'Sc4m(m)',
 'Sc4m(o)',
 'Sc4m(r)',
 'Sc4t',
 'Sc4t(d)',
 'Sc4t(i)',
 'Sc4t(l)',
 'Sc4t(m)',
 'Sc4t(o)',
 'Sc4t(r)',
 'Sc4t(u)',
 'Sc?l',
 'Sc?l(d)',
 'Sc?l(i)',
 'Sc?l(l)',
 'Sc?l(m)',
 'Sc?l(o)',
 'Sc?l(r)',
 'Sc?m',
 'Sc?m(d)',
 'Sc?m(i)',
 'Sc?m(l)',
 'Sc?m(m)',
 'Sc?m(o)',
 'Sc?m(r)',
 'Sc?m(u)',
 'Sc?t',
 'Sc?t(d)',
 'Sc?t(i)',
 'Sc?t(l)',
 'Sc?t(m)',
 'Sc?t(o)',
 'Sc?t(r)',
 'Sc?t(u)',
 'Sd',
 'Sd(d)',
 'Sd(i)',
 'Sd(l)',
 'Sd(m)',
 'Sd(o)',
 'Sd(r)',
 'Sd(u)',
 'Sd+l',
 'Sd+m',
 'Sd+m(d)',
 'Sd+m(i)',
 'Sd+m(o)',
 'Sd+t',
 'Sd+t(d)',
 'Sd1l',
 'Sd1l(d)',
 'Sd1l(i)',
 'Sd1l(m)',
 'Sd1l(o)',
 'Sd1l(r)',
 'Sd1m',
 'Sd1m(d)',
 'Sd1m(i)',
 'Sd1m(m)',
 'Sd1m(o)',
 'Sd1m(r)',
 'Sd1t',
 'Sd1t(d)',
 'Sd1t(i)',
 'Sd1t(m)',
 'Sd1t(o)',
 'Sd1t(r)',
 'Sd2l',
 'Sd2l(d)',
 'Sd2l(i)',
 'Sd2l(m)',
 'Sd2l(o)',
 'Sd2l(r)',
 'Sd2m',
 'Sd2m(d)',
 'Sd2m(i)',
 'Sd2m(o)',
 'Sd2m(r)',
 'Sd2t',
 'Sd2t(i)',
 'Sd2t(m)',
 'Sd2t(o)',
 'Sd2t(r)',
 'Sd3l',
 'Sd3l(i)',
 'Sd3m',
 'Sd3m(i)',
 'Sd3m(o)',
 'Sd3t',
 'Sd3t(i)',
 'Sd3t(o)',
 'Sd4l',
 'Sd4l(i)',
 'Sd4l(m)',
 'Sd4m',
 'Sd4m(i)',
 'Sd4t',
 'Sd4t(i)',
 'Sd?l',
 'Sd?l(d)',
 'Sd?l(i)',
 'Sd?l(m)',
 'Sd?m',
 'Sd?m(i)',
 'Sd?m(m)',
 'Sd?m(o)',
 'Sd?m(r)',
 'Sd?t',
 'Sd?t(d)',
 'Sd?t(i)',
 'Sd?t(m)',
 'Sd?t(o)',
 'Sd?t(r)',
 'Seb',
 'Seb(i)',
 'Seb(m)',
 'Seb(u)',
 'Sen',
 'Sen(d)',
 'Sen(i)',
 'Sen(m)',
 'Sen(o)',
 'Sen(r)',
 'Sen(u)',
 'Ser',
 'Ser(d)',
 'Ser(i)',
 'Ser(l)',
 'Ser(m)',
 'Ser(o)',
 'Ser(r)',
 'Ser(u)']

In [5]:
# Show column names in first dataset
df.columns

Index(['objid', 'sample', 'asset_id'], dtype='object')

image

In [12]:
import os
from PIL import Image
# Folder where raw images 
raw_dir = r"C:\Users\khali\Synoptic Project\images_gz2\images"
# Get all image files ending with valid 
image_files = [f for f in os.listdir(raw_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]  # keep only images

# Print total number of images found
print(f"Total images found: {len(image_files)}")
# Print first 10 image filenames
print("First 10 images:", image_files[:10])
# Pick first image 
sample_image_path = os.path.join(raw_dir, image_files[0])
# Open the image using PIL
img = Image.open(sample_image_path)
# Display image 
img.show()
# Print image size so width or height and mode so RGB, grayscale
print(f"Image size: {img.size}, mode: {img.mode}")

Total images found: 243434
First 10 images: ['100.jpg', '1000.jpg', '10000.jpg', '100000.jpg', '100001.jpg', '100002.jpg', '100003.jpg', '100004.jpg', '100005.jpg', '100006.jpg']
Image size: (424, 424), mode: RGB

merge

In [7]:
# Rename column so both datasets match on same key
df = df.rename(columns={'objid': 'dr7objid'})

In [8]:
# Merge both datasets using shared ID column
merged_df = pd.merge(df1, df, on='dr7objid')

In [15]:
# Show merged result
merged_df.head()

,dr7objid,ra,dec,rastring,decstring,sample_x,gz2_class,total_classifications,total_votes,t01_smooth_or_features_a01_smooth_count,...,t11_arms_number_a36_more_than_4_debiased,t11_arms_number_a36_more_than_4_flag,t11_arms_number_a37_cant_tell_count,t11_arms_number_a37_cant_tell_weight,t11_arms_number_a37_cant_tell_fraction,t11_arms_number_a37_cant_tell_weighted_fraction,t11_arms_number_a37_cant_tell_debiased,t11_arms_number_a37_cant_tell_flag,sample_y,asset_id
0,587732591714893851,179.042984,60.522518,11:56:10.32,+60:31:21.1,original,Sc+t,45,342,0,...,0.482646,0,16,16.0,0.400,0.400,0.394506,0,original,58957
1,588009368545984617,135.084396,52.494240,09:00:20.26,+52:29:39.3,original,Sb+t,42,332,1,...,0.504833,0,13,13.0,0.317,0.323,0.322743,0,original,193641
2,587732484359913515,183.371979,50.741508,12:13:29.27,+50:44:29.4,original,Ei,36,125,28,...,0.000000,0,0,0.0,0.000,0.000,0.000000,0,original,55934
3,587741723357282317,186.251953,28.558598,12:25:00.47,+28:33:31.0,original,Sc+t,28,218,1,...,0.241322,0,6,6.0,0.240,0.240,0.239765,0,original,158501
4,587738410866966577,161.086395,14.084465,10:44:20.73,+14:05:04.1,original,Er,43,151,33,...,0.000000,0,0,0.0,0.000,0.000,0.000000,0,original,110939

In [11]:
# Save merged dataset to a new CSV file
merged_df.to_csv('merged_data.csv', index=False)

Organize Images by Class

In [12]:
import os
import shutil
import re
from tqdm import tqdm  # progress bar

# Path where raw images
raw_images_dir = r"C:\Users\khali\Synoptic Project\images_gz2\images"
# Output folder for organized dataset
output_dir = r"C:\Users\khali\Synoptic Project\dataset_gz2"
# Function to remove illegal characters from folder names
def sanitize(name):
    return re.sub(r'[\\/*?:"<>|]', "_", name)

# Get all unique galaxy classes
classes = merged_df['gz2_class'].unique()
# Create a folder for each class
for cls in classes:
    os.makedirs(os.path.join(output_dir, sanitize(cls)), exist_ok=True)
# Loop through dataset rows one by one
for _, row in tqdm(merged_df.iterrows(), total=len(merged_df), desc="Copying images"):
    asset_id = str(row['asset_id']) # image ID
    label = sanitize(row['gz2_class']) # class label

    found = False # track if image is found
    # Try different image extensions
    for ext in ['.jpg', '.jpeg', '.png']: 
                # Build filename
        filename = f"{asset_id}{ext}"
          # Full path to image
        src = os.path.join(raw_images_dir, filename)
        # If image exists
        if os.path.exists(src):
         # Destination path
            dst = os.path.join(output_dir, label, filename)
                        # Copy image to class folder
            shutil.copy2(src, dst)
            found = True
            break
    # If image not found print warning

    if not found:
        tqdm.write(f"Warning: {asset_id} not found")

Copying images:   1%|▋                                                          | 2788/239695 [00:25<22:44, 173.63it/s]

Warning: 26603 not found

Copying images:   1%|▋                                                          | 2971/239695 [00:26<22:28, 175.60it/s]

Warning: 222471 not found

Copying images:   5%|███                                                       | 12810/239695 [01:31<26:53, 140.59it/s]

Warning: 7350 not found

Copying images:   6%|███▎                                                      | 13675/239695 [01:37<24:07, 156.19it/s]

Warning: 59271 not found

Copying images:   6%|███▌                                                       | 14409/239695 [01:42<45:15, 82.97it/s]

Warning: 33878 not found

Copying images:   6%|███▌                                                      | 14661/239695 [01:44<21:12, 176.83it/s]

Warning: 203731 not found

Copying images:   8%|████▍                                                     | 18569/239695 [02:10<25:19, 145.53it/s]

Warning: 285103 not found

Copying images:   9%|█████▎                                                    | 21759/239695 [02:31<20:49, 174.44it/s]

Warning: 215414 not found

Copying images:   9%|█████▎                                                    | 22187/239695 [02:34<19:57, 181.66it/s]

Warning: 99869 not found

Copying images:  11%|██████                                                   | 25257/239695 [03:01<3:11:58, 18.62it/s]

Warning: 102663 not found

Copying images:  13%|███████▎                                                  | 30225/239695 [03:32<21:18, 163.85it/s]

Warning: 59270 not found

Copying images:  14%|████████▎                                                 | 34555/239695 [03:59<22:15, 153.62it/s]

Warning: 102665 not found

Copying images:  15%|████████▍                                                 | 34840/239695 [04:01<24:25, 139.82it/s]

Warning: 15247 not found

Copying images:  15%|████████▍                                                 | 35017/239695 [04:02<21:05, 161.75it/s]

Warning: 249103 not found

Copying images:  16%|█████████▍                                                | 39064/239695 [04:28<19:25, 172.16it/s]

Warning: 249590 not found

Copying images:  17%|█████████▉                                                | 41023/239695 [04:41<21:03, 157.19it/s]

Warning: 99870 not found

Copying images:  19%|███████████                                               | 45655/239695 [05:11<18:33, 174.24it/s]

Warning: 219381 not found

Copying images:  21%|████████████▎                                             | 50909/239695 [05:49<17:45, 177.14it/s]

Warning: 59269 not found

Copying images:  23%|█████████████▍                                            | 55307/239695 [06:17<18:16, 168.20it/s]

Warning: 50643 not found

Copying images:  27%|███████████████▋                                          | 64815/239695 [07:15<17:37, 165.42it/s]

Warning: 33877 not found

Copying images:  28%|████████████████                                          | 66536/239695 [07:26<16:37, 173.64it/s]

Warning: 293834 not found

Copying images:  31%|█████████████████▉                                        | 74314/239695 [08:16<16:08, 170.77it/s]

Warning: 293831 not found

Copying images:  37%|█████████████████████▌                                    | 89354/239695 [09:57<14:12, 176.45it/s]

Warning: 33876 not found

Copying images:  37%|█████████████████████▋                                    | 89409/239695 [09:57<14:09, 176.87it/s]

Warning: 95667 not found

Copying images:  37%|█████████████████████▋                                    | 89796/239695 [10:00<15:00, 166.53it/s]

Warning: 203682 not found

Copying images:  37%|█████████████████████▋                                    | 89872/239695 [10:00<14:04, 177.45it/s]

Warning: 198041 not found

Copying images:  38%|█████████████████████▊                                    | 90327/239695 [10:03<13:39, 182.23it/s]

Warning: 216810 not found

Copying images:  45%|█████████████████████████▊                               | 108359/239695 [11:56<13:31, 161.86it/s]

Warning: 252151 not found

Copying images:  45%|█████████████████████████▉                               | 108848/239695 [12:00<12:10, 179.13it/s]

Warning: 15246 not found

Copying images:  47%|██████████████████████████▉                              | 113061/239695 [12:31<17:17, 122.07it/s]

Warning: 218989 not found

Copying images:  48%|███████████████████████████▍                             | 115466/239695 [12:45<12:05, 171.20it/s]

Warning: 221376 not found

Copying images:  49%|███████████████████████████▊                             | 116863/239695 [12:54<11:08, 183.76it/s]

Warning: 203683 not found

Copying images:  50%|████████████████████████████▎                            | 119179/239695 [13:08<11:19, 177.23it/s]

Warning: 7351 not found

Copying images:  50%|████████████████████████████▌                            | 120253/239695 [13:15<12:13, 162.75it/s]

Warning: 10959 not found

Copying images:  51%|████████████████████████████▊                            | 121156/239695 [13:21<17:30, 112.80it/s]

Warning: 26606 not found

Copying images:  51%|█████████████████████████████                            | 122158/239695 [13:27<13:14, 147.89it/s]

Warning: 273522 not found

Copying images:  54%|██████████████████████████████▋                          | 128802/239695 [14:10<10:41, 172.93it/s]

Warning: 191283 not found

Copying images:  54%|██████████████████████████████▉                          | 130029/239695 [14:18<10:33, 173.00it/s]

Warning: 7349 not found

Copying images:  57%|████████████████████████████████▋                        | 137401/239695 [15:13<11:14, 151.65it/s]

Warning: 203681 not found

Copying images:  59%|█████████████████████████████████▋                       | 141568/239695 [15:39<08:58, 182.36it/s]

Warning: 270604 not found

Copying images:  61%|██████████████████████████████████▋                      | 145966/239695 [16:07<08:38, 180.65it/s]

Warning: 215411 not found

Copying images:  61%|██████████████████████████████████▋                      | 146100/239695 [16:07<08:33, 182.31it/s]

Warning: 40057 not found

Copying images:  61%|███████████████████████████████████                      | 147391/239695 [16:16<08:58, 171.48it/s]

Warning: 92317 not found

Copying images:  62%|███████████████████████████████████▌                     | 149351/239695 [16:28<08:55, 168.79it/s]

Warning: 203684 not found

Copying images:  63%|███████████████████████████████████▊                     | 150685/239695 [16:36<08:45, 169.34it/s]

Warning: 242804 not found

Copying images:  64%|████████████████████████████████████▏                    | 152272/239695 [16:45<07:57, 183.00it/s]

Warning: 81483 not found

Copying images:  64%|████████████████████████████████████▍                    | 153088/239695 [16:50<07:53, 182.93it/s]

Warning: 89792 not found

Copying images:  69%|███████████████████████████████████████▍                 | 166079/239695 [18:04<06:43, 182.62it/s]

Warning: 293833 not found

Copying images:  69%|███████████████████████████████████████▌                 | 166325/239695 [18:06<06:41, 182.86it/s]

Warning: 247974 not found

Copying images:  70%|███████████████████████████████████████▋                 | 167104/239695 [18:10<06:27, 187.41it/s]

Warning: 271224 not found

Copying images:  71%|████████████████████████████████████████▍                | 170126/239695 [18:27<06:29, 178.46it/s]

Warning: 27513 not found

Copying images:  72%|█████████████████████████████████████████▏               | 173358/239695 [18:47<06:28, 170.56it/s]

Warning: 198346 not found

Copying images:  76%|███████████████████████████████████████████▍             | 182689/239695 [19:41<05:15, 180.69it/s]

Warning: 203736 not found

Copying images:  77%|███████████████████████████████████████████▊             | 183998/239695 [19:49<05:06, 181.55it/s]

Warning: 252457 not found

Copying images:  79%|████████████████████████████████████████████▉            | 188907/239695 [20:17<04:42, 179.57it/s]

Warning: 30336 not found

Copying images:  80%|█████████████████████████████████████████████▍           | 190975/239695 [20:29<05:02, 161.30it/s]

Warning: 198345 not found

Copying images:  82%|██████████████████████████████████████████████▌          | 195784/239695 [20:57<04:26, 164.90it/s]

Warning: 242803 not found

Copying images:  83%|███████████████████████████████████████████████▌         | 200076/239695 [21:23<03:48, 173.12it/s]

Warning: 215412 not found

Copying images:  87%|█████████████████████████████████████████████████▌       | 208622/239695 [22:13<03:01, 171.65it/s]

Warning: 198040 not found

Copying images:  90%|███████████████████████████████████████████████████▏     | 215408/239695 [22:59<02:17, 176.01it/s]

Warning: 27514 not found

Copying images:  91%|████████████████████████████████████████████████████     | 219194/239695 [23:21<02:00, 170.22it/s]

Warning: 274093 not found
Warning: 274131 not found
Warning: 274197 not found
Warning: 274564 not found
Warning: 274709 not found
Warning: 274964 not found
Warning: 275032 not found
Warning: 275489 not found
Warning: 275615 not found
Warning: 275917 not found
Warning: 275971 not found
Warning: 275972 not found
Warning: 275973 not found
Warning: 276498 not found
Warning: 276927 not found
Warning: 277280 not found
Warning: 277669 not found
Warning: 278074 not found
Warning: 278075 not found
Warning: 278078 not found
Warning: 278111 not found
Warning: 278702 not found
Warning: 280163 not found
Warning: 280856 not found
Warning: 281128 not found
Warning: 281129 not found
Warning: 281130 not found
Warning: 282534 not found
Warning: 283507 not found
Warning: 283829 not found
Warning: 284389 not found
Warning: 284390 not found
Warning: 285937 not found
Warning: 286733 not found
Warning: 286946 not found

Copying images:  91%|████████████████████████████████████████████████████▏    | 219229/239695 [23:21<02:01, 168.48it/s]

Warning: 287209 not found
Warning: 287211 not found
Warning: 287247 not found
Warning: 287445 not found
Warning: 287733 not found
Warning: 288251 not found
Warning: 288327 not found
Warning: 288793 not found
Warning: 288795 not found
Warning: 288796 not found
Warning: 289083 not found
Warning: 290772 not found
Warning: 291585 not found
Warning: 292644 not found
Warning: 293322 not found
Warning: 293324 not found
Warning: 294225 not found

Copying images:  92%|████████████████████████████████████████████████████▎    | 220184/239695 [23:27<01:54, 170.89it/s]

Warning: 198348 not found

Copying images:  92%|████████████████████████████████████████████████████▍    | 220523/239695 [23:29<01:51, 172.36it/s]

Warning: 374 not found

Copying images:  92%|████████████████████████████████████████████████████▌    | 220987/239695 [23:32<01:58, 157.26it/s]

Warning: 242802 not found

Copying images:  93%|████████████████████████████████████████████████████▊    | 221989/239695 [23:38<01:46, 166.90it/s]

Warning: 198347 not found

Copying images:  96%|██████████████████████████████████████████████████████▊  | 230289/239695 [24:27<00:52, 178.43it/s]

Warning: 198350 not found

Copying images: 100%|████████████████████████████████████████████████████████▊| 238919/239695 [25:17<00:04, 158.92it/s]

Warning: 198349 not found

Copying images: 100%|█████████████████████████████████████████████████████████| 239695/239695 [25:21<00:00, 157.50it/s]

Warning: 275883 not found
Warning: 282536 not found
Warning: 284172 not found
Warning: 288961 not found

Main Classes

In [1]:
import os
import shutil
from tqdm import tqdm  # progress bar

# Input folder 
source_dir = r"C:\Users\khali\Synoptic Project\dataset_gz2"
# Output folder
target_dir = r"C:\Users\khali\Synoptic Project\dataset_gz2_main"
# Function to map detailed labels into main categories
def map_to_main_class(label):
     # If label starts with SB it go to Barred Spiral
    if label.startswith('SB'):
        return 'Barred_Spiral'
            # If label starts with E it go to Elliptical galaxy
    elif label.startswith('E'):
        return 'Elliptical'
            # If label starts with S it go to Spiral galaxy
    elif label.startswith('S'):
        return 'Spiral'
            # Otherwise Irregular type
    else:
        return 'Irregular'
#  main class folders
main_classes = ['Barred_Spiral', 'Elliptical', 'Spiral']
# Create folders for main classes
for cls in main_classes:
    os.makedirs(os.path.join(target_dir, cls), exist_ok=True)

# Count total files for progress bar
total_files = 0
    # Only count folders
for folder in os.listdir(source_dir):
    src_path = os.path.join(source_dir, folder)
    if os.path.isdir(src_path):
        total_files += len(os.listdir(src_path))

# Progress bar while moving files
with tqdm(total=total_files, desc="Moving files") as pbar:
# Loop through each subclass folder
    for folder in sorted(os.listdir(source_dir)):
        src_path = os.path.join(source_dir, folder)

        if not os.path.isdir(src_path):
            continue
        # Get main class name
        main_class = map_to_main_class(folder)
                # Destination folder
        dst_folder = os.path.join(target_dir, main_class)
        # Loop through images in folder
        for file in sorted(os.listdir(src_path)):
            src_file = os.path.join(src_path, file)

            if os.path.isfile(src_file):

                dst_file = os.path.join(dst_folder, file)

                # Avoid duplicate filenames
                counter = 1
                base_name, ext = os.path.splitext(file)

                while os.path.exists(dst_file):
                    dst_file = os.path.join(
                        dst_folder,
                        f"{base_name}_copy{counter}{ext}"
                    )
                    counter += 1

                shutil.move(src_file, dst_file)

                pbar.update(1)

print(" Main class organization complete.")

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\khali\\Synoptic Project\\dataset_gz2'

In [18]:
for cls in main_classes:
    class_path = os.path.join(target_dir, cls)
    count = len([f for f in os.listdir(class_path)
                 if os.path.isfile(os.path.join(class_path, f))])
    print(f"{cls}: {count}")

Barred_Spiral: 45568
Elliptical: 90772
Spiral: 95818

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\khali\\Synoptic Project\\dataset_gz2_main\\Irregular'

SPLIT

In [24]:
import os
import shutil
import random
from tqdm import tqdm

# dataset folder
source_dir = r"C:\Users\khali\Synoptic Project\dataset_gz2V2"
# Output split dataset folder
output_dir = r"C:\Users\khali\Synoptic Project\dataset_split2"

# Ratios for splitting data
train_ratio = 0.7
val_ratio = 0.15
test_ratio = 0.15

# Define dataset splits
splits = ['train', 'val', 'test']
# Create folder structure
for split in splits:
    for class_name in os.listdir(source_dir):
        class_path = os.path.join(source_dir, class_name)
        if os.path.isdir(class_path):
            os.makedirs(os.path.join(output_dir, split, class_name), exist_ok=True)

# Loop through each class
for class_name in os.listdir(source_dir):
    class_path = os.path.join(source_dir, class_name)

    if not os.path.isdir(class_path):
        continue
    # Get all images
    images = os.listdir(class_path)
    random.shuffle(images)
    # calculate split indices
    total = len(images)
    train_end = int(train_ratio * total)
    val_end = int((train_ratio + val_ratio) * total)
    # Split data
    train_imgs = images[:train_end]
    val_imgs = images[train_end:val_end]
    test_imgs = images[val_end:]

    # Copy training images
    for img in tqdm(train_imgs, desc=f"{class_name} - Train"):
        shutil.copy2(
            os.path.join(class_path, img),
            os.path.join(output_dir, 'train', class_name, img)
        )
    # Copy validation images
    for img in tqdm(val_imgs, desc=f"{class_name} - Val"):
        shutil.copy2(
            os.path.join(class_path, img),
            os.path.join(output_dir, 'val', class_name, img)
        )
    # Copy test images
    for img in tqdm(test_imgs, desc=f"{class_name} - Test"):
        shutil.copy2(
            os.path.join(class_path, img),
            os.path.join(output_dir, 'test', class_name, img)
        )

print("\n Dataset successfully split!")
print(" Output folder:", output_dir)

Barred spiral - Train: 100%|████████████████████████████████████████████████████| 20913/20913 [00:55<00:00, 376.04it/s]
Barred spiral - Val: 100%|████████████████████████████████████████████████████████| 4482/4482 [00:11<00:00, 384.25it/s]
Barred spiral - Test: 100%|███████████████████████████████████████████████████████| 4482/4482 [00:11<00:00, 384.44it/s]
Disk galaxy - Train: 100%|██████████████████████████████████████████████████████| 11629/11629 [00:30<00:00, 386.03it/s]
Disk galaxy - Val: 100%|██████████████████████████████████████████████████████████| 2492/2492 [00:06<00:00, 370.19it/s]
Disk galaxy - Test: 100%|█████████████████████████████████████████████████████████| 2493/2493 [00:06<00:00, 377.28it/s]
Elliptical galaxy - Train: 100%|████████████████████████████████████████████████| 34451/34451 [01:29<00:00, 383.19it/s]
Elliptical galaxy - Val: 100%|████████████████████████████████████████████████████| 7383/7383 [00:18<00:00, 390.35it/s]
Elliptical galaxy - Test: 100%|███████████████████████████████████████████████████| 7383/7383 [00:19<00:00, 379.18it/s]
Irregular - Train: 100%|██████████████████████████████████████████████████████████| 3988/3988 [00:09<00:00, 405.82it/s]
Irregular - Val: 100%|██████████████████████████████████████████████████████████████| 855/855 [00:02<00:00, 387.20it/s]
Irregular - Test: 100%|█████████████████████████████████████████████████████████████| 855/855 [00:02<00:00, 387.04it/s]
Lenticular galaxy - Train: 100%|██████████████████████████████████████████████████| 3082/3082 [00:07<00:00, 388.68it/s]
Lenticular galaxy - Val: 100%|██████████████████████████████████████████████████████| 660/660 [00:01<00:00, 424.92it/s]
Lenticular galaxy - Test: 100%|█████████████████████████████████████████████████████| 661/661 [00:01<00:00, 390.33it/s]
Merger - Train: 100%|█████████████████████████████████████████████████████████████| 1635/1635 [00:04<00:00, 391.10it/s]
Merger - Val: 100%|█████████████████████████████████████████████████████████████████| 351/351 [00:00<00:00, 418.88it/s]
Merger - Test: 100%|████████████████████████████████████████████████████████████████| 351/351 [00:00<00:00, 382.25it/s]
Spiral galaxy - Train: 100%|████████████████████████████████████████████████████| 33651/33651 [01:24<00:00, 396.86it/s]
Spiral galaxy - Val: 100%|████████████████████████████████████████████████████████| 7211/7211 [00:18<00:00, 384.59it/s]
Spiral galaxy - Test: 100%|███████████████████████████████████████████████████████| 7211/7211 [00:18<00:00, 389.70it/s]

✅ Dataset successfully split!
📁 Output folder: C:\Users\khali\Synoptic Project\dataset_split2

Clean Corrupted Images

In [ ]:
from PIL import Image
import os
from tqdm import tqdm

# Function to clean dataset
def clean_dataset(root_dir, name="dataset"):

    broken_files = []  # store corrupted images
    total_files = 0

    # Count all images
    for folder in os.listdir(root_dir):
        folder_path = os.path.join(root_dir, folder)

        if os.path.isdir(folder_path):
            total_files += len(os.listdir(folder_path))

    print(f"Checking {name}: {total_files} images")

    # Progress bar
    with tqdm(total=total_files, desc=f"Cleaning {name}") as pbar:

        for folder in os.listdir(root_dir):

            folder_path = os.path.join(root_dir, folder)

            if not os.path.isdir(folder_path):
                continue

            for file in os.listdir(folder_path):

                file_path = os.path.join(folder_path, file)

                try:
                    img = Image.open(file_path)
                    img.verify()  # check if image is valid

                except:
                    print(f"Removing broken image: {file_path}")
                    broken_files.append(file_path)
                    os.remove(file_path)

                pbar.update(1)

    print(f"{name} cleaning complete")
    print(f"Removed {len(broken_files)} images")

    return len(broken_files)

train_dir = r"C:\Users\khali\Synoptic Project\dataset_split\train"
val_dir   = r"C:\Users\khali\Synoptic Project\dataset_split\val"
test_dir  = r"C:\Users\khali\Synoptic Project\dataset_split\test"

print("STARTING DATASET CLEANING...\n")

train_removed = clean_dataset(train_dir, "TRAIN")
val_removed   = clean_dataset(val_dir, "VAL")
test_removed  = clean_dataset(test_dir, "TEST")

print("FINAL SUMMARY")
print("Train removed:", train_removed)
print("Val removed:", val_removed)
print("Test removed:", test_removed)

Dataset Balancing and  Augmentation

In [ ]:
import os  # Used for file/folder operations (create, list directories)
import random  
import shutil  # Used to copy files from one folder to another
from PIL import Image 
from torchvision import transforms  
from tqdm import tqdm 

# Path to training dataset (input images grouped by class)
input_dir = r"C:\Users\khali\Synoptic Project\dataset_split\train"

# Path where balanced dataset will be saved
output_dir = r"C:\Users\khali\Synoptic Project\dataset_balanced\train"

# Target number of images per class 
target_size = 67000  

# Define augmentation pipeline 
augment = transforms.Compose([
    transforms.RandomHorizontalFlip(),  # Flip image left-right randomly
    transforms.RandomRotation(20),  # Rotate image randomly up to ±20 degrees
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),  # Crop + resize image
])

# Create output directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Loop through each class folder 
for class_name in os.listdir(input_dir):

    # Full path to current class folder
    class_path = os.path.join(input_dir, class_name)

    # Output folder for this class
    output_class_path = os.path.join(output_dir, class_name)

    # Skip if not a folder 
    if not os.path.isdir(class_path):
        continue

    # Create output class folder
    os.makedirs(output_class_path, exist_ok=True)

    # Get all image files in this class folder
    images = [
        f for f in os.listdir(class_path)
        if f.lower().endswith(('.png', '.jpg', '.jpeg'))  # only images
    ]

    # Count how many images exist in this class
    current_count = len(images)

    # Print class information
    print(f"\n {class_name}: {current_count}")

   
    if current_count > target_size:

        # Randomly pick only target_size images
        selected = random.sample(images, target_size)

        # Copy selected images to new folder
        for img_name in tqdm(selected, desc=f"{class_name} (copying)"):

            src = os.path.join(class_path, img_name)  # source image path
            dst = os.path.join(output_class_path, img_name)  # destination

            shutil.copy2(src, dst)  # copy image file


    else:

        # First copy ALL original images
        for img_name in tqdm(images, desc=f"{class_name} (copying originals)"):

            src = os.path.join(class_path, img_name)
            dst = os.path.join(output_class_path, img_name)

            shutil.copy2(src, dst)

        # Calculate how many new images we need to create
        needed = target_size - current_count

        print(f"Augmenting {needed} images for {class_name}")

        i = 0  # counter for new images

        # Progress bar for augmentation process
        pbar = tqdm(total=needed, desc=f"{class_name} (augmenting)")

        # Keep generating images until we reach target size
        while i < needed:

            # Randomly pick an existing image
            img_name = random.choice(images)

            # Full image path
            img_path = os.path.join(class_path, img_name)

            try:
                # Open image and convert to RGB format
                img = Image.open(img_path).convert("RGB")

                # Apply random augmentation transformations
                aug_img = augment(img)

                # Create new unique filename
                new_name = f"aug_{i}_{img_name}"

                # Save augmented image
                aug_img.save(os.path.join(output_class_path, new_name))

                # Increase counter
                i += 1

                # Update progress bar
                pbar.update(1)

            except:
                # If image fails  skip it
                continue

        # Close progress bar
        pbar.close()

# Final message
print("\n Dataset balanced successfully!")